translations = {
    "title": "FreeLaserDesigns 激光切割素材",
    "search": "搜索素材...",
    "upload": "上传素材",
    "login": "登录",
    "logout": "登出",
    "welcome": "欢迎",
    "detail": "详情页面",
    "category": "分类",
    "download": "下载文件",
    "back": "返回首页",
    "username": "用户名",
    "password": "密码",
    "submit": "提交",
    "invalid": "用户名或密码错误",
    "upload_title": "上传激光切割素材",
    "label_title": "标题",
    "label_category": "分类",
    "label_file": "上传文件",
    "label_thumb": "上传缩略图",
    "language": "语言",
    "chinese": "中文",
    "english": "English"
}
