translations = {
    "title": "FreeLaserDesigns Laser Cut Designs",
    "search": "Search designs...",
    "upload": "Upload Design",
    "login": "Login",
    "logout": "Logout",
    "welcome": "Welcome",
    "detail": "Design Detail",
    "category": "Category",
    "download": "Download File",
    "back": "Back to Home",
    "username": "Username",
    "password": "Password",
    "submit": "Submit",
    "invalid": "Invalid username or password",
    "upload_title": "Upload Laser Cut Design",
    "label_title": "Title",
    "label_category": "Category",
    "label_file": "Upload File",
    "label_thumb": "Upload Thumbnail",
    "language": "Language",
    "chinese": "中文",
    "english": "English"
}
